apiVersion: v1
kind: Service
metadata:
  name: hiap-meed-service-dev
  namespace: default
  labels:
    app: hiap-meed-dev
spec:
  selector:
    app: hiap-meed-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP

