apiVersion: v1
kind: Service
metadata:
  name: hiap-meed-service-test
  namespace: default
  labels:
    app: hiap-meed-test
spec:
  selector:
    app: hiap-meed-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP

