apiVersion: v1
kind: ConfigMap
metadata:
  name: climate-advisor-db-configmap-prod
  namespace: default
data:
  DB_HOST: "oef-prod-db.cluster-ck89kopkx0x4.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "climateadvisor"
  DB_PASSWORD: "climateadvisor"
  DB_NAME: "climateadvisor"
  DB_URL: "postgresql://climateadvisor:climateadvisor@oef-prod-db.cluster-ck89kopkx0x4.us-east-1.rds.amazonaws.com/climateadvisor"
  CA_DATABASE_URL: "postgresql://climateadvisor:climateadvisor@oef-prod-db.cluster-ck89kopkx0x4.us-east-1.rds.amazonaws.com/climateadvisor"
