apiVersion: v1
kind: Service
metadata:
  name: climate-advisor-service-dev
  namespace: default
  labels:
    app: climate-advisor-dev
spec:
  selector:
    app: climate-advisor-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
